#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanningWebApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="gmprint_zmv")]
	public partial class StoredProceduresDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public StoredProceduresDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["gmprint_zmvConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StoredProceduresDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StoredProceduresDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StoredProceduresDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StoredProceduresDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.P_PLN_WebGetOperatons")]
		public ISingleResult<P_PLN_WebGetOperatonsResult> P_PLN_WebGetOperatons()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<P_PLN_WebGetOperatonsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PLN_WebGetDays")]
		public ISingleResult<PLN_WebGetDaysResult> PLN_WebGetDays()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<PLN_WebGetDaysResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.P_PLN_GetPlanOperations")]
		public ISingleResult<P_PLN_GetPlanOperationsResult> P_PLN_GetPlanOperations([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idWorkshop, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dDateBgn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dDateEnd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idWorkshop, dDateBgn, dDateEnd);
			return ((ISingleResult<P_PLN_GetPlanOperationsResult>)(result.ReturnValue));
		}
	}
	
	public partial class P_PLN_WebGetOperatonsResult
	{
		
		private int _ID;
		
		private string _MachineName;
		
		private System.Nullable<int> _TimeStart;
		
		private System.Nullable<int> _TimeEnd;
		
		private System.Nullable<int> _TypeOpeation;
		
		public P_PLN_WebGetOperatonsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineName", DbType="NVarChar(1024)")]
		public string MachineName
		{
			get
			{
				return this._MachineName;
			}
			set
			{
				if ((this._MachineName != value))
				{
					this._MachineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeStart", DbType="Int")]
		public System.Nullable<int> TimeStart
		{
			get
			{
				return this._TimeStart;
			}
			set
			{
				if ((this._TimeStart != value))
				{
					this._TimeStart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeEnd", DbType="Int")]
		public System.Nullable<int> TimeEnd
		{
			get
			{
				return this._TimeEnd;
			}
			set
			{
				if ((this._TimeEnd != value))
				{
					this._TimeEnd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOpeation", DbType="Int")]
		public System.Nullable<int> TypeOpeation
		{
			get
			{
				return this._TypeOpeation;
			}
			set
			{
				if ((this._TypeOpeation != value))
				{
					this._TypeOpeation = value;
				}
			}
		}
	}
	
	public partial class PLN_WebGetDaysResult
	{
		
		private System.Nullable<int> _hr;
		
		private System.Nullable<System.DateTime> _dt;
		
		private string _descr;
		
		public PLN_WebGetDaysResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hr", DbType="Int")]
		public System.Nullable<int> hr
		{
			get
			{
				return this._hr;
			}
			set
			{
				if ((this._hr != value))
				{
					this._hr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dt", DbType="DateTime")]
		public System.Nullable<System.DateTime> dt
		{
			get
			{
				return this._dt;
			}
			set
			{
				if ((this._dt != value))
				{
					this._dt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descr", DbType="NVarChar(1024)")]
		public string descr
		{
			get
			{
				return this._descr;
			}
			set
			{
				if ((this._descr != value))
				{
					this._descr = value;
				}
			}
		}
	}
	
	public partial class P_PLN_GetPlanOperationsResult
	{
		
		private long _ID;
		
		private int _TypeData;
		
		private string _Workshop;
		
		private string _OrderNumber;
		
		private string _TypeUrgency;
		
		private string _Machine;
		
		private string _Operation;
		
		private string _OperationDescription;
		
		private string _FormatSize;
		
		private System.Nullable<System.DateTime> _DateBgnPlan;
		
		private System.Nullable<System.DateTime> _DateEndPlan;
		
		private System.Nullable<double> _DurPlanInMi;
		
		private System.Nullable<double> _DurPlanInHh;
		
		private string _NameProduct;
		
		private System.Nullable<int> _Circulation;
		
		private System.Nullable<System.DateTime> _DateCalcComplete;
		
		public P_PLN_GetPlanOperationsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeData", DbType="Int NOT NULL")]
		public int TypeData
		{
			get
			{
				return this._TypeData;
			}
			set
			{
				if ((this._TypeData != value))
				{
					this._TypeData = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Workshop", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Workshop
		{
			get
			{
				return this._Workshop;
			}
			set
			{
				if ((this._Workshop != value))
				{
					this._Workshop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNumber", DbType="NVarChar(100)")]
		public string OrderNumber
		{
			get
			{
				return this._OrderNumber;
			}
			set
			{
				if ((this._OrderNumber != value))
				{
					this._OrderNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeUrgency", DbType="VarChar(18)")]
		public string TypeUrgency
		{
			get
			{
				return this._TypeUrgency;
			}
			set
			{
				if ((this._TypeUrgency != value))
				{
					this._TypeUrgency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Machine", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Machine
		{
			get
			{
				return this._Machine;
			}
			set
			{
				if ((this._Machine != value))
				{
					this._Machine = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operation", DbType="NVarChar(50)")]
		public string Operation
		{
			get
			{
				return this._Operation;
			}
			set
			{
				if ((this._Operation != value))
				{
					this._Operation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperationDescription", DbType="NVarChar(1000)")]
		public string OperationDescription
		{
			get
			{
				return this._OperationDescription;
			}
			set
			{
				if ((this._OperationDescription != value))
				{
					this._OperationDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormatSize", DbType="NVarChar(61)")]
		public string FormatSize
		{
			get
			{
				return this._FormatSize;
			}
			set
			{
				if ((this._FormatSize != value))
				{
					this._FormatSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateBgnPlan", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateBgnPlan
		{
			get
			{
				return this._DateBgnPlan;
			}
			set
			{
				if ((this._DateBgnPlan != value))
				{
					this._DateBgnPlan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEndPlan", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateEndPlan
		{
			get
			{
				return this._DateEndPlan;
			}
			set
			{
				if ((this._DateEndPlan != value))
				{
					this._DateEndPlan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DurPlanInMi", DbType="Float")]
		public System.Nullable<double> DurPlanInMi
		{
			get
			{
				return this._DurPlanInMi;
			}
			set
			{
				if ((this._DurPlanInMi != value))
				{
					this._DurPlanInMi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DurPlanInHh", DbType="Float")]
		public System.Nullable<double> DurPlanInHh
		{
			get
			{
				return this._DurPlanInHh;
			}
			set
			{
				if ((this._DurPlanInHh != value))
				{
					this._DurPlanInHh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameProduct", DbType="NVarChar(100)")]
		public string NameProduct
		{
			get
			{
				return this._NameProduct;
			}
			set
			{
				if ((this._NameProduct != value))
				{
					this._NameProduct = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Circulation", DbType="Int")]
		public System.Nullable<int> Circulation
		{
			get
			{
				return this._Circulation;
			}
			set
			{
				if ((this._Circulation != value))
				{
					this._Circulation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCalcComplete", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCalcComplete
		{
			get
			{
				return this._DateCalcComplete;
			}
			set
			{
				if ((this._DateCalcComplete != value))
				{
					this._DateCalcComplete = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
